.PHONY: clean All

All:
	@echo "----------Building project:[ challenge_three - Debug ]----------"
	@cd "challenge_three" && "$(MAKE)" -f  "challenge_three.mk"
clean:
	@echo "----------Cleaning project:[ challenge_three - Debug ]----------"
	@cd "challenge_three" && "$(MAKE)" -f  "challenge_three.mk" clean
