.PHONY: clean All

All:
	@echo "----------Building project:[ task_one - Debug ]----------"
	@cd "task_one" && "$(MAKE)" -f  "task_one.mk"
clean:
	@echo "----------Cleaning project:[ task_one - Debug ]----------"
	@cd "task_one" && "$(MAKE)" -f  "task_one.mk" clean
