.PHONY: clean All

All:
	@echo "----------Building project:[ user_input_test - Debug ]----------"
	@cd "user_input_test" && "$(MAKE)" -f  "user_input_test.mk"
clean:
	@echo "----------Cleaning project:[ user_input_test - Debug ]----------"
	@cd "user_input_test" && "$(MAKE)" -f  "user_input_test.mk" clean
